### ISSUE TITLE
need an apk

### ISSUE THREAD

**Issue by navlaw** [PyojinKim/Sensors-Data-Logger#1]
Hi, I don't know how to generate an apk because I don't know much about Android programming, could you please upload the packaged apk?

**Comment by PyojinKim** [comment]
Hi navlaw,

This is quite an old Android project, so currently, I have no Android studio to produce apk file for this app.
However, once you take the Android programming 101 lecture (about 10 mins?), you can easily build this app.

Thanks,
Pyojin Kim.
